checklist-after/config/routes.rb
Checklist::Application.routes.draw do
  resources :tasks
  root to: 'tasks#index'
end

checklist-after/app/models/task.rb
class Task < ActiveRecord::Base
  attr_accessible :complete, :name
end

checklist-after/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

checklist-after/app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index
    sleep 1
    @incomplete_tasks = Task.where(complete: false)
    @complete_tasks = Task.where(complete: true)
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.create!(params[:task])
    respond_to do |format|
      format.html { redirect_to tasks_url }
      format.js
    end
  end

  def update
    @task = Task.find(params[:id])
    @task.update_attributes!(params[:task])
    respond_to do |format|
      format.html { redirect_to tasks_url }
      format.js
    end
  end

  def destroy
    @task = Task.destroy(params[:id])
    respond_to do |format|
      format.html { redirect_to tasks_url }
      format.js
    end
  end
end

checklist-after/app/helpers/application_helper.rb
module ApplicationHelper
end

checklist-after/app/helpers/tasks_helper.rb
module TasksHelper
end

checklist-after/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Check List</title>
    <%= stylesheet_link_tag    "application", media: "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tag %>
  </head>
  <body>
    <div id="container">
      <% flash.each do |name, msg| %>
        <%= content_tag :div, msg, id: "flash_#{name}" %>
      <% end %>
      <%= yield %>
    </div>
  </body>
</html>

checklist-after/app/views/tasks/_form.html.erb
<%= form_for @task, remote: true do |f| %>
  <%= f.text_field :name %>
  <%= f.submit %>
<% end %>

checklist-after/app/views/tasks/_task.html.erb
<%= form_for task, remote: true do |f| %>
  <%= f.check_box :complete %>
  <%= f.submit "Update" %>
  <%= f.label :complete, task.name %>
  <%= link_to "(remove)", task, method: :delete, data: {confirm: "Are you sure?"}, remote: true %>
<% end %>

checklist-after/app/views/tasks/create.js.erb
$('#new_task').remove();
$('#new_link').show();
$('#incomplete_tasks').append('<%= j render(@task) %>');
$('#edit_task_<%= @task.id %>').submitOnCheck();

checklist-after/app/views/tasks/destroy.js.erb
$('#edit_task_<%= @task.id %>').remove();

checklist-after/app/views/tasks/index.html.erb
<h1>Check List</h1>

<%= link_to "New Task", new_task_path, id: "new_link", remote: true %>

<h2>Incomplete Tasks</h2>
<div class="tasks" id="incomplete_tasks">
  <%= render @incomplete_tasks %>
</div>

<h2>Comlpete Tasks</h2>
<div class="tasks" id="complete_tasks">
  <%= render @complete_tasks %>
</div>

checklist-after/app/views/tasks/new.html.erb
<h1>New Task</h1>

<%= render 'form' %>

<p><%= link_to "Back to tasks", tasks_path %></p>

checklist-after/app/views/tasks/new.js.erb
$('#new_link').hide().after('<%= j render("form") %>');

checklist-after/app/views/tasks/update.js.erb
<% if @task.complete? %>
  $('#edit_task_<%= @task.id %>').appendTo('#complete_tasks');
<% else %>
  $('#edit_task_<%= @task.id %>').appendTo('#incomplete_tasks');
<% end %>